### ISSUE TITLE
Replace moment.js

### ISSUE THREAD

**Issue by ngehlert** [jonsamp/date-streaks#2]
Are you willing to accept a PR to remove moment() as dependency and use something more lightweigt?

Or instead a PR to at least only import the needed functions from moment instead of the entire lib?

**Comment by jonsamp** [comment]
Yes, this is a great improvement idea and one im working on right now. I'm going to convert this lib to use [date-fns](https://date-fns.org/). If you have another lib in mind, let me know. But this one seems popular and vastly smaller and faster than moment.

**Comment by ngehlert** [comment]
sounds awesome. yes I would've chosen date-fns as well. let me know if you need any help :)

**Comment by jonsamp** [comment]
I just published a new version that replaces moment with date-fns 🎉 

You can see the entire PR here if you're interested: https://github.com/jonsamp/date-streaks/pull/4

Also, here's a graph showing the size decrease after conversion. Great improvement!
<img width="594" alt="Screen Shot 2019-05-10 at 9 44 50 PM" src="https://user-images.githubusercontent.com/6455018/57565142-e8beee80-736c-11e9-9a21-6a6b3993ee00.png">


... Now on to adding a an `index.d.ts`

**Comment by ngehlert** [comment]
you are awesome. thanks for your work
