### ISSUE TITLE
Upgrade to TypeScript

### ISSUE THREAD

**Issue by ngehlert** [jonsamp/date-streaks#3]
Are there any plans or intentions to upgrade to Typescript or provide typings so it can better be used in projects that use typescript?

**Comment by jonsamp** [comment]
Another great improvement! As I'm working on this lib, I can add some typings as well. I'll update here when the new release is ready to go!

**Comment by jonsamp** [comment]
Added types! Please update to version `1.1.6` 

https://github.com/jonsamp/date-streaks/blob/master/index.d.ts

**Comment by ngehlert** [comment]
that was fast. thanks 👍
