### ISSUE TITLE
I'm not able to get any streaks calculated with my array of dates

### ISSUE THREAD

**Issue by ozgecokyasar** [jonsamp/date-streaks#5]
Here is my array, which I copied from the console:
0: Sun Sep 08 2019 21:45:53 GMT+0100 (British Summer Time) {}
1: Sun Sep 08 2019 23:14:41 GMT+0100 (British Summer Time) {}
2: Wed Sep 04 2019 17:50:23 GMT+0100 (British Summer Time) {}
3: Sun Sep 08 2019 18:17:42 GMT+0100 (British Summer Time) {}
4: Sun Sep 08 2019 18:18:17 GMT+0100 (British Summer Time) {}
5: Sun Sep 08 2019 18:18:50 GMT+0100 (British Summer Time) {}
6: Sun Sep 08 2019 18:20:07 GMT+0100 (British Summer Time) {}
7: Sun Sep 08 2019 18:22:14 GMT+0100 (British Summer Time) {}
8: Sun Sep 08 2019 19:18:56 GMT+0100 (British Summer Time) {}
9: Sun Sep 08 2019 19:19:19 GMT+0100 (British Summer Time) {}
10: Sun Sep 08 2019 19:23:26 GMT+0100 (British Summer Time) {}

When I call summary({}) with the above data, I get the following object, which is not the correct calculation:
currentStreak: 0
longestStreak: 0
streaks: [1]
todayInStreak: false
withinCurrentStreak: false
__proto__: Object

On the other hand, when I use a fake data set, it works perfectly well.
  const dates = [
      new Date('01/01/2018'),
      new Date('01/02/2018'),
      new Date('01/04/2018')
    ];
summary({dates}), gives me the correct calculations.

**Comment by gugacavalieri** [comment]
Hey @ozgecokyasar. It happened to me as well.

The problem was in the object I was passing to the `summary({})` function. It must have the `dates` property in it.

This should work:

`summary({ dates: myDateArray }) `

@jonsamp do you think the API be more friendly and accept and array as input as well? I could work on this if you think it's a good move :)

**Comment by jonsamp** [comment]
@gugacavalieri that seems reasonable to me! If you want to work on it, I'm happy to review a PR. Also happy to do this myself if you're busy. Lmk if you want to take this on!

**Comment by gugacavalieri** [comment]
Cool! I think I can help with that :)

Will check if the parameter is an array. I can send you the PR :smile:
